version: '3.7'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.23
    command: >
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --default-storage-engine=innodb
      --max-allowed-packet=16M
      --innodb-flush-log-at-trx-commit=2
      --disable-log-bin
      --sql-mode=
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
volumes:
  mysql-data:
